### ISSUE TITLE
Not implemented correctly.

### ISSUE THREAD

**Issue by GravisZro** [kassane/sieve-cache-cpp#1]
This doesn't implement SIEVE correctly.

Specifically, I see no indication that...
* a record is made when a node has been visited, the core mechanism used in cache eviction.
* cache eviction ever happens

**Comment by kassane** [comment]
Hi @GravisZro,

Yes, this remake is not following the original proposal and does not match the Dlang implementation.
It's not ideal and I'll need to review the current implementation.

This current implementation was a response to the initial proposal below.
https://github.com/kassane/sieve-cache-cpp/commit/20cdbd1c8758319364db6f7afe4e3f7d0b98e349

The Benchmark previously carried out based on the old implementation, resulting poor performance with `std::unordered_map`.

**Comment by GravisZro** [comment]
My suggestion is to revert to the poorly performing version that worked correctly and then modify it. Slow is always better than non-functional.

**Comment by kassane** [comment]
> My suggestion is to revert to the poorly performing version that worked correctly and then modify it. Slow is always better than non-functional.

Ok! I do. https://github.com/kassane/sieve-cache-cpp/commit/f9825c9d40d49dd51322225c614eeaeba96a3331
